CREATE TABLE IF NOT EXISTS `fa_chat_rp_auto_task` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(64) NOT NULL DEFAULT '' COMMENT '任务名',
  `group_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '群ID',
  `send_user_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '发包用户ID(首个,兼容)',
  `send_user_ids` varchar(512) NOT NULL DEFAULT '' COMMENT '发包UID逗号分隔,空则用send_user_id',
  `packet_type` tinyint(3) unsigned NOT NULL DEFAULT '2' COMMENT '1均分2手气3埋雷5接龙',
  `total_amount` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '兼容展示=amount_min',
  `amount_min` decimal(12,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '金额下限(=上限则固定)',
  `amount_max` decimal(12,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '金额上限(=下限则固定)',
  `amount_mode` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT '1=区间 2=小额10-100+每10-20包插发200-300;接龙强制1',
  `amount_mode2_count` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '模式二：自上次大奖后已发小额包数',
  `amount_mode2_target` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '模式二：下次大奖前小额包数阈值(10-20)',
  `amount_mode2_jackpot_min` decimal(12,2) unsigned NOT NULL DEFAULT '200.00' COMMENT '模式二大奖下限',
  `amount_mode2_jackpot_max` decimal(12,2) unsigned NOT NULL DEFAULT '300.00' COMMENT '模式二大奖上限',
  `amount_mode2_every_min` int(10) unsigned NOT NULL DEFAULT '10' COMMENT '模式二：多少小额包后插大奖(下限)',
  `amount_mode2_every_max` int(10) unsigned NOT NULL DEFAULT '20' COMMENT '模式二：多少小额包后插大奖(上限)',
  `total_count` int(10) unsigned NOT NULL DEFAULT '5',
  `blessing` varchar(128) NOT NULL DEFAULT '恭喜发财',
  `mine_digit` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '废弃:埋雷改为每次随机0-9',
  `interval_sec` int(10) unsigned NOT NULL DEFAULT '60' COMMENT '自动发包间隔秒(仅群内无待领包时)',
  `interval_windows` text NULL COMMENT '时段固定间隔JSON [{start_hour,end_hour,interval_sec}]',
  `burst_count` int(10) unsigned NOT NULL DEFAULT '1' COMMENT '突发窗内发包数,1=不用突发',
  `burst_window_sec` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '突发时间窗秒,0=沿用间隔秒',
  `burst_window_start` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '当前时间窗起点unix',
  `burst_sent` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '当前窗已发包数',
  `burst_next_at` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '窗内下一次计划发包unix',
  `auto_send` tinyint(1) NOT NULL DEFAULT '1',
  `continuous_send` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '1=持续发(有未领完也可发);接龙任务忽略',
  `auto_grab` tinyint(1) NOT NULL DEFAULT '1',
  `actor_mode` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT '1=发包/抢包UID池 2=机器人账户随机发抢',
  `grab_user_ids` varchar(512) NOT NULL DEFAULT '' COMMENT '抢包机器人UID,逗号分隔',
  `grab_delay_min_ms` int(10) unsigned NOT NULL DEFAULT '5000' COMMENT '抢包延迟最小ms(建议5000=5秒)',
  `grab_delay_max_ms` int(10) unsigned NOT NULL DEFAULT '15000' COMMENT '抢包延迟最大ms(建议15000=15秒)',
  `max_per_day` int(10) unsigned NOT NULL DEFAULT '100' COMMENT '每日最多发包次数,0不限',
  `today_date` date DEFAULT NULL,
  `today_count` int(10) unsigned NOT NULL DEFAULT '0',
  `last_send_time` int(10) unsigned NOT NULL DEFAULT '0',
  `last_packet_id` int(10) unsigned NOT NULL DEFAULT '0',
  `last_error` varchar(255) NOT NULL DEFAULT '',
  `status` enum('normal','hidden') NOT NULL DEFAULT 'hidden' COMMENT 'normal=启用',
  `remark` varchar(255) NOT NULL DEFAULT '',
  `createtime` int(10) unsigned DEFAULT NULL,
  `updatetime` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_status_group` (`status`,`group_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='红包自动发抢任务';
