CREATE TABLE IF NOT EXISTS `fa_chat_rp_rain_task` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(64) NOT NULL DEFAULT '' COMMENT '任务名',
  `group_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '群ID',
  `send_user_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '发包用户ID(首个,兼容)',
  `send_user_ids` varchar(512) NOT NULL DEFAULT '' COMMENT '发包UID逗号分隔',
  `packet_type` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT '1普通红宝 4随机红宝',
  `total_amount` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '兼容展示=amount_min',
  `amount_min` decimal(12,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '金额下限',
  `amount_max` decimal(12,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '金额上限',
  `total_count` int(10) unsigned NOT NULL DEFAULT '5' COMMENT '每包份数',
  `blessing` varchar(128) NOT NULL DEFAULT '恭喜发财',
  `actor_mode` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT '1=UID池 2=机器人账户',
  `auto_send` tinyint(1) NOT NULL DEFAULT '1',
  `auto_grab` tinyint(1) NOT NULL DEFAULT '1',
  `grab_user_ids` varchar(512) NOT NULL DEFAULT '' COMMENT '抢包UID逗号分隔',
  `grab_delay_min_ms` int(10) unsigned NOT NULL DEFAULT '5000',
  `grab_delay_max_ms` int(10) unsigned NOT NULL DEFAULT '15000',
  `time_slots` text COMMENT '模式1开启时间JSON [{time:HH:MM,count:发包次数}]',
  `schedule_mode` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT '1定点时刻 2每N分钟',
  `interval_minutes` int(10) unsigned NOT NULL DEFAULT '5' COMMENT '模式2:每隔多少分钟',
  `interval_count` int(10) unsigned NOT NULL DEFAULT '1' COMMENT '模式2:每轮发包数',
  `bot_grab_cap` int(10) unsigned NOT NULL DEFAULT '1' COMMENT '每机器人每轮最多抢几个包,0不限',
  `bot_grab_pct` tinyint(3) unsigned NOT NULL DEFAULT '80' COMMENT '超时前机器人最多抢本轮包数的百分比',
  `sweep_minutes` int(10) unsigned NOT NULL DEFAULT '3' COMMENT '超过N分钟后机器人领完剩余',
  `last_slot_key` varchar(64) NOT NULL DEFAULT '' COMMENT '已触发轮次标记',
  `last_round_start` int(10) unsigned NOT NULL DEFAULT '0',
  `round_packet_ids` text COMMENT '本轮红包ID逗号分隔',
  `round_target` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '本轮计划发包数',
  `round_sent` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '本轮已发包数(抢完再发下一包)',
  `force_send` tinyint(1) NOT NULL DEFAULT '0' COMMENT '1=下一次tick立即发一轮',
  `last_packet_id` int(10) unsigned NOT NULL DEFAULT '0',
  `last_error` varchar(255) NOT NULL DEFAULT '',
  `status` enum('normal','hidden') NOT NULL DEFAULT 'hidden' COMMENT 'normal=启用',
  `remark` varchar(255) NOT NULL DEFAULT '',
  `createtime` int(10) unsigned DEFAULT NULL,
  `updatetime` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_status_group` (`status`,`group_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='红宝雨机器人';
